import type { Settings } from './types'

export function getDefaultSettings(): Settings {
  return {
    providers: {
      openai: { type: 'openai', baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini' },
      claude: { type: 'claude', baseUrl: 'https://api.anthropic.com', model: 'claude-3-5-sonnet-20241022' },
      gemini: { type: 'gemini', baseUrl: 'https://generativelanguage.googleapis.com', model: 'gemini-1.5-flash' },
      ollama: { type: 'ollama', baseUrl: 'http://localhost:11434', model: 'llama3.2' },
      openrouter: { type: 'openrouter', baseUrl: 'https://openrouter.ai/api/v1', model: 'openai/gpt-4o-mini' },
      vllm: { type: 'vllm', baseUrl: 'http://localhost:8000/v1', model: 'qwen2.5-7b-instruct' },
      lmstudio: { type: 'lmstudio', baseUrl: 'http://localhost:1234/v1', model: 'qwen2.5-7b-instruct' },
      tabby: { type: 'tabby', baseUrl: 'http://localhost:5000/v1', model: 'model' },
      deepseek: { type: 'deepseek', baseUrl: 'https://api.deepseek.com', model: 'deepseek-chat' },
      groq: { type: 'groq', baseUrl: 'https://api.groq.com/openai/v1', model: 'llama-3.3-70b-versatile' },
      siliconflow: { type: 'siliconflow', baseUrl: 'https://api.siliconflow.cn/v1', model: 'deepseek-ai/DeepSeek-V3' },
    },
    connectionProfiles: [],
    activeProfileId: null,
    activeModel: 'gpt-4o-mini',
    activePresetId: 'builtin-default',
    activeCharacterId: null,
    activeSessionId: null,
    theme: 'dark',
    themeColor: 'amber',
    fontSize: 'comfortable',
    fontSizeCustom: 0,
    bubbleStyle: 'round',
    messageSpacing: 20,
    messageWidth: 768,
    streamOutput: true,
    autoScroll: true,
    defaultMemoryEnabled: false,
    defaultNarrativeMode: 'immersive',
    continueIntensity: 'active',
    continueLength: 'standard',
    defaultResponseLength: 'auto',
    reasoningEffort: 'auto',
    autoTailRepairEnabled: true,
    costReminderEnabled: true,
    ttsEnabled: false,
    ttsModels: [],
    activeTTSModelId: null,
    imageGenModels: [],
    activeImageGenModelId: null,
    visionModels: [],
    activeVisionModelId: null,
    userName: '用户',
    userDescription: '',
    userPersona: '',
    activePersonaId: null,
    defaultPersonaId: null,
    htmlRendering: false,
    // 字符数 chip 默认关闭：阅读流里属开发者视角元信息，可在快捷设置打开
    showTokenCount: false,
    enableThoughtFormat: true,
    autoExpandThought: false,
    exampleDialogMode: 'always',
    coverBlurStrength: 8,
    enableUsageTracking: true,
    useCoverAsBackground: false,
    translationTargetLang: '中文',
    coverProxyUrl: '',
    fontFamily: 'system',
    customFontId: null,
    semanticTrigger: {
      enabled: false,
      provider: 'ollama',
      baseUrl: 'http://localhost:11434',
      model: 'nomic-embed-text',
      apiKey: '',
      thresholdMode: 'auto',
      threshold: 0.3,
      maxResults: 3,
    },
    localModels: {
      retrievalMode: 'auto',
      autoIndex: true,
      updatePolicy: 'notify',
      idleOnly: true,
      batchSize: 8,
    },
    personaInjection: {
      enabled: true,
      position: 'system',
      includeDescription: true,
      includePersona: true,
    },
    contextCompression: {
      enabled: true,
      minDropTokens: 2000,
    },
    autoTitle: true,
    // W10：G1 已通过；新安装默认启用，存量明确值由 v3→v4 迁移保留。
    reasoningGateEnabled: true,
  }
}
