import type { Settings } from './types'

export function getDefaultSettings(): Settings {
  return {
    activeProvider: 'openai',
    providers: {
      openai: { type: 'openai', baseUrl: 'https://api.openai.com/v1', model: 'gpt-4o-mini' },
      claude: { type: 'claude', baseUrl: 'https://api.anthropic.com', model: 'claude-3-5-sonnet-20241022' },
      gemini: { type: 'gemini', baseUrl: 'https://generativelanguage.googleapis.com', model: 'gemini-1.5-flash' },
      ollama: { type: 'ollama', baseUrl: 'http://localhost:11434', model: 'llama3.2' },
    },
    connectionProfiles: [],
    activeProfileId: null,
    activeModel: 'gpt-4o-mini',
    activePresetId: 'builtin-default',
    activeCharacterId: null,
    activeSessionId: null,
    theme: 'dark',
    themeColor: 'amber',
    fontSize: 'comfortable',
    fontSizeCustom: 0,
    bubbleStyle: 'round',
    messageSpacing: 20,
    messageWidth: 768,
    streamOutput: true,
    autoScroll: true,
    ttsEnabled: false,
    ttsModels: [],
    activeTTSModelId: null,
    imageGenModels: [],
    activeImageGenModelId: null,
    visionModels: [],
    activeVisionModelId: null,
    userName: '用户',
    userDescription: '',
    userPersona: '',
    activePersonaId: null,
    defaultPersonaId: null,
    htmlRendering: false,
    showTokenCount: true,
    enableThoughtFormat: true,
    autoExpandThought: false,
    coverBlurStrength: 8,
    enableUsageTracking: true,
    useCoverAsBackground: false,
    translationTargetLang: '中文',
    coverProxyUrl: 'http://127.0.0.1:7890',
    fontFamily: 'system',
    customFontId: null,
    pricingRules: [
      { id: 'builtin-gpt4o', modelPattern: 'gpt-4o*', inputPricePer1M: 2.5, outputPricePer1M: 10, isBuiltin: true },
      { id: 'builtin-gpt4o-mini', modelPattern: 'gpt-4o-mini*', inputPricePer1M: 0.15, outputPricePer1M: 0.6, isBuiltin: true },
      { id: 'builtin-claude35', modelPattern: 'claude-3-5*', inputPricePer1M: 3, outputPricePer1M: 15, isBuiltin: true },
      { id: 'builtin-claude37', modelPattern: 'claude-3-7*', inputPricePer1M: 3, outputPricePer1M: 15, isBuiltin: true },
      { id: 'builtin-gemini', modelPattern: 'gemini-*', inputPricePer1M: 1.25, outputPricePer1M: 5, isBuiltin: true },
      { id: 'builtin-deepseek', modelPattern: 'deepseek*', inputPricePer1M: 0.14, outputPricePer1M: 0.28, isBuiltin: true },
      { id: 'builtin-qwen', modelPattern: 'qwen*', inputPricePer1M: 0.5, outputPricePer1M: 1.5, isBuiltin: true },
    ],
  }
}
